### ISSUE TITLE
docs: dynamic modules (vuex modules stored in a different folder) asyncData not working

### ISSUE THREAD

**Issue by electronrecord** [danielroe/typed-vuex#151]
Hi Daniel, I have a nuxt.js project with typescript vuex and my CTO decided to have the root/modules folder in which to declare 
the app modules.

So in this folder, I have a module called init-case which has a store inside. So we are talking here about dynamic modules, as described on your docs: /modules/init-case/store/initCase.ts

I am trying to call the asyncData from the .vue file inside these modules, but it seems that I cannot resolve this functionality.
I have recorded a loom for better details.

thank you.

https://www.loom.com/share/598336b4c5d948b39fe1ec07b3ca60df

**Comment by danielroe** [comment]
I suspect that `asyncData` is being called before your component `created` hook. So the dynamic module isn't present at that point. You could try moving your module-creation logic into the new-style `fetch` hook?

**Comment by electronrecord** [comment]
well, all I need is to dispatch the initiateData action on the SSR, no matter if is asyncData or fetch. So, do u think that fetch will do the job to dispatch the action on the server, get the data and render back the component with the prefilled data?

many thanks

**Comment by electronrecord** [comment]
nope, the same problem, I cannot access the initialize action in the asyncData, even if I fetch instead of created.
But do u have any idea why beforeCreate does not work? I mean, does it work on you, the example that u have in docs at Dynamic Modules section? Cause is it now working on my side

**Comment by danielroe** [comment]
@electronrecord It's difficult without being able to edit your code, but I mean move stuff in asyncData into `fetch` - as the issue is that asyncData is being called *before* created/fetch.

**Comment by electronrecord** [comment]
so, I have tried that, but without luck...

here is my code in .vue file:

```
fetch({ app }) {
    console.log(app.$accessor.emails);
    return app.$accessor;
  },
  created() {
    this.$store.registerModule('initCase', initCase, {
      preserveState: false,
    });
    const accessor = useAccessor(this.$store, initCase, 'initCase');
    accessor.addEmail('my@email.com');
    this.accessor = accessor;
  },
```
and here in the store that I register (initCase.ts)
```
import { actionTree, mutationTree } from 'nuxt-typed-vuex';
import axios from 'axios';

export interface ICStore {
  emails?: string[];
}

export const state = (): ICStore => ({
  emails: ['vasea'] as string[],
});
...
```

So the problem is that in fetch I do not have access to the store.
But if I try to access some state var from the /store/index.ts it does work. So is somehow related with registering store modules.

How do you do it on your projects?

**Comment by danielroe** [comment]
When I say the new-style fetch I mean not taking an argument ([see docs](https://nuxtjs.org/api/pages-fetch/#nuxt--212)).

Try something like this:
```js
  // ...
  fetch() {
    this.registerModule()
    console.log(this.$accessor.emails);
    this.emails = this.$accessor.emails
  },
  data: () => ({
    accessor: null
  }),
  methods: {
    registerModule() {
      if (this.accessor) return
      this.$store.registerModule('initCase', initCase, {
        preserveState: false,
      });
      this.accessor = useAccessor(this.$store, initCase, 'initCase');
    }
  },
```

**Comment by electronrecord** [comment]
aha, let me try that.

**Comment by electronrecord** [comment]
ok, so is starting to work partially, meaning that the action initialise from the store module initCase does get called.
But, I think I was unclear in what I want to achieve:

using your library nuxt-typed-vuex, I want to have a store module in /modules root folder, and when the page is created, to populate the data of that page already on the server side (SSR). As you already know, this is done in a normal nuxt project without typescript by using asyncData which returns a store action.

Question: how can I render data on the page on the server using nuxt-typed-vuex with dynamic module?

Because maybe my code example is wrong and I am willing to change the implementation to meet the requirements.

thanks

**Comment by danielroe** [comment]
Any better for you?
```js
  // ...
  asyncData({ store }) {
    this.$store.registerModule('initCase', initCase, {
      preserveState: false,
    });
    const accessor = useAccessor(this.$store, initCase, 'initCase');
    return { accessor }
  },
  data: () => ({
    accessor: null,
  }),
```

**Comment by electronrecord** [comment]
good morning Daniel, 
I have tried your last sugestion as follows:
```
 asyncData({ store }) {
    store.registerModule('initCase', initCase, {
      preserveState: false,
    });
    const accessor = useAccessor(store, initCase, 'initCase');
    return accessor.initialise();
  },
```
This indeed will dispatch the initialize action, but, to render in component I need to use {{ $store.state.initCase.emails }}, considering that I have a emails array on the initCase store modules, and the initialize action will push an email address to this array.

But besides the state of the initCase module, I cannot access dispatch or commit. So doing "this.$store.commit('initCase.addEmails' or 'initCase/addEmails', email@address.com) will not work.

Any suggestion in getting the accessor in the vue page? 
Note: in asyncData we don't have access to this, so we cannot declare something like this.accessor = accessor

many thanks && awaiting for your response.

**Comment by danielroe** [comment]
@electronrecord Sorry for never replying! If you create a codesandbox reproduction, I'll happily have a play around.

**Comment by electronrecord** [comment]
hi Daniel, no worries, I've moved out from that project, was something from the past job :)) but I think is great that you have replied, even a bit later ;)
