### ISSUE TITLE
quest: How to set up multi-level module

### ISSUE THREAD

**Issue by StringKe** [danielroe/typed-vuex#159]
How to set up multi-level moudle？

```
rootVuex:{
  ui:{
    left:{

    }
  },
  user:{}
}
```

```
import * as user from './user';
import * as ui from './ui';
import * as left from './ui/left';
```
how to set the `left` module ?

**Comment by StringKe** [comment]
![image](https://user-images.githubusercontent.com/31089228/92369152-35fecc00-f12b-11ea-8d2d-7da83a258614.png)

**Comment by danielroe** [comment]
@StringKe I think it should just work as long as you include a modules key:

```ts
const storePattern = {
  state,
  getters,
  modules: {
    design: {
      state,
      modules: {
        ui: {
          state
        }
      }
    }
  }
}
```

Let me know if that's not the case.
