### ISSUE TITLE
docs: how to test actions

### ISSUE THREAD

**Issue by manuel-84** [danielroe/typed-vuex#160]
how do you write jest tests for components using this.$accessor to call an action?

**Comment by danielroe** [comment]
@manuel-84 in general mocking the store during jest tests asks you to make a number of decisions which I can't answer for you. But if you want to create an $accessor during jest testing, you can do so following [these instructions](https://typed-vuex.roe.dev/customisation).

Alternatively, you can of course simply mock the accessor with something like:
```ts
const mockAccessor = jest.fn()
Vue.prototype.$accessor = mockAccessor
```

If you have any other questions, please do get back to me with some code and I'll see what I can do to help.

**Comment by manuel-84** [comment]
I ended up mocking it this way with vue/test-utils

    wrapper = shallowMount(myComponent, {
      mocks: {
        $accessor: {
          login: jest.fn(() => {
            return new Promise.resolve({
                response: {
                  data: { myDataMock }
                }
              })
            })
          }),
          get_user: jest.fn(() => Promise.resolve()),
        },
      },
      localVue
    })
