### ISSUE TITLE
How to get store data out of vue component such as in plugin?

### ISSUE THREAD

**Issue by JanusSpark** [danielroe/typed-vuex#171]
I want to use store's state data in this plugin
what should I do ?

When I try to use Vue.prototye.$accessor,it returned an undefined.
And When I try to get Vue.prototye.$accessor in setTimeout,it throw an error: "Uncaught TypeError: Cannot read property '$options' of undefined"

this is a minimal repro.
https://codesandbox.io/s/practical-aryabhata-nw931?file=/plugins/report.ts

I hope I made it clear

Thanks

**Comment by danielroe** [comment]
@JanusSpark Would you be happy to use it in a plugin that accesses the Nuxt context, or do you want to use it just in the body of the file?

**Comment by JanusSpark** [comment]
> @JanusSpark Would you be happy to use it in a plugin that accesses the Nuxt context, or do you want to use it just in the body of the file?

I think both methods should solve the problem.I just don't know how to get the Nuxt context or how to get the  instance of the store in the plugin file...

**Comment by P4sca1** [comment]
@JenusSpark
```ts
import type { Plugin } from '@nuxt/types'

const myPlugin: Plugin = (ctx) => {
  // You have access to the typed store accessor using ctx.app.$accessor
  ctx.app.$accessor.someProperty
}

export default myPlugin
```

**Comment by danielroe** [comment]
@P4sca1 thanks! - and apologies @JanusSpark that I missed your reply.

**Comment by JanusSpark** [comment]
> @JanusSpark
> 
> ```ts
> import type { Plugin } from '@nuxt/types'
> 
> const myPlugin: Plugin = (ctx) => {
>   // You have access to the typed store accessor using ctx.app.$accessor
>   ctx.app.$accessor.someProperty
> }
> 
> export default myPlugin
> ```

@P4sca1 Thanks~It works~
@danielroe Thank you all the same.You helped me a lot about Nuxt
