### ISSUE TITLE
Make clear that state, mutations and actions all should have different names

### ISSUE THREAD

**Issue by P4sca1** [danielroe/typed-vuex#176]
**📚 Is your documentation request related to a problem? Please describe.**
I ran into the  following error after migrating my store to `typed-vuex`:
```
Cannot set property connected of #<Object> which has only a getter
```
This error does not contain much detail and was quite hard to debug. I figured it was caused by having a mutation that is named the same as a state property. So I had `state.connected` and a `connected` mutation.
While I should've named my mutation `setConnected` and it is not common to have the same name for state and mutations or actions, it is something that works in plain vuex but is a limitation of `typed-vuex`.

It would be great if this would be noticed as a warning in the docs.

**Comment by danielroe** [comment]
Good point! I've added a notice. Does that seem sufficient to you?

**Comment by P4sca1** [comment]
Yes, thats perfect. Thank you!
