### ISSUE TITLE
docs: how to mock app in actions

### ISSUE THREAD

**Issue by alrayyes** [danielroe/typed-vuex#179]
As I understand it you're supposed to use this.app to reference other modules in actions (ie this.app.$axios). In unit tests I keep getting a "Cannot read property '$axios' of undefined" message for my action code:

```js
const workspaces: Array<Workspace> = await this.app.$axios.$get(
          'https://example.com',
          {
            auth: apiLogin,
          }
        )
```

The factory method I use to test the store:

```js
function factory({ promise = Promise.resolve({}) as Promise<any> }) {
  jest.mock('axios')
  const mockNuxtAxios = axios as jest.Mocked<NuxtAxiosInstance>
  mockNuxtAxios.$get = jest.fn().mockReturnValue(promise)

  const localVue = createLocalVue()
  localVue.use(Vuex)

  const store = new Vuex.Store({ state, mutations, actions, getters })

  return useAccessor(store, {
    state,
    mutations,
    actions,
    getters,
  })
}
```

Is there an easy way to do something like

```js
actions.app = {$axios: mockNuxtAxios}
```

**Comment by danielroe** [comment]
@alrayyes have you tried just setting `localVue.app = { $axios: mockNuxtAxios }`?

**Comment by alrayyes** [comment]
Yup. That gives a `TS2339: Property 'app' does not exist on type 'VueConstructor '.` error and doesn't seem to solve the issue `TypeError: Cannot read property '$axios' of undefined
`

**Comment by danielroe** [comment]
Ah - of course, you'll want to set it on the `store`. Try `;(store as any).app = { $axios: mockNuxtAxios }`

**Comment by alrayyes** [comment]
That did the trick, thanks a bunch!
