### ISSUE TITLE
Missing link in docs

### ISSUE THREAD

**Issue by filippolcr** [danielroe/typed-vuex#181]
**🐛 The bug**
What isn't working? Describe what the bug is.
Ehi Man! I just want to typing my accessor and it's better with your guide. 🤙🏻
The link in the docs is missing. [https://typed-vuex.roe.dev/setup.html#add-type-definitions](https://typed-vuex.roe.dev/setup.html#add-type-definitions)

**🛠️ To reproduce**
Just surf [https://typed-vuex.roe.dev/accessor-introduction](https://typed-vuex.roe.dev/accessor-introduction)

**🌈 Expected behaviour**
No Missing link

**ℹ️ Additional context**
Thanks for typed-vuex

**Comment by danielroe** [comment]
Thanks @filippolcr :heart:
