### ISSUE TITLE
docs:  Can't set the state properly with a mutation

### ISSUE THREAD

**Issue by filippolcr** [danielroe/typed-vuex#183]
**📚 Is your documentation request related to a problem? Please describe.**

I've an store/account.ts module.
Here the relevant part to address my issue. (I'm using Helper functions)

```
export const state = () => ({
  isAuthenticated: false as boolean,
  user: {} as any,
)}
```

```
export const mutations = mutationTree(state, {
  setUser(state, newUser: any) {
    console.log('1', newUser)
    console.log('2', state.user)
    state.isAuthenticated = !!newUser
    state.user = newUser
},
```

and an action that commit **setUser** mutation

```
export const actions = actionTree(
  { state, getters, mutations },
  {
    async load({ commit, dispatch, getters, state }) {
      try {
        const user = await getAuthenticatedUser()
        this.app.$accessor.account.setUser(user)
      } catch (error) {
        this.app.$accessor.account.setUser(null)
      }
    },
```

If inspect the console.log('1', newUser) I have the expected object, but when I want to set in state with the mutation, the state is not updated correctly.

If I inspect the console.log('2', state.user) I see this:

```
{__ob__: Observer}
__ob__: Observer {value: {…}, dep: Dep, vmCount: 0}
__proto__: Object
```

Can you clarify what's happening here?
I don't think this is an issue, but my mistake in the implementation phase

**🔍 Where should you find it?**
[https://typed-vuex.roe.dev/build](https://typed-vuex.roe.dev/build)
[https://typed-vuex.roe.dev/mutations](https://typed-vuex.roe.dev/mutations)

**ℹ️ Additional context**
I provide the store/index.ts here:

```
import { GetterTree, MutationTree, ActionTree } from 'vuex'

import { getAccessorType } from 'typed-vuex'

import * as module1 from '~/store/module1'
import * as accountModule from '~/store/account'

export const state = () => ({})

export type RootState = ReturnType<typeof state>

export const getters: GetterTree<RootState, RootState> = {}

export const mutations: MutationTree<RootState> = {}

export const actions: ActionTree<RootState, RootState> = {
  nuxtServerInit ({ dispatch, commit }) {
    console.log(dispatch, commit)
  },
}

// TODO: improve types
export const accessorType: any = getAccessorType({
  state,
  getters,
  mutations,
  actions,
  modules: {
    module1,
    accountModule
  }
})

**Comment by danielroe** [comment]
@filippolcr It looks like you are logging the state before updating it. What makes you think that the mutation has failed? If it is that the user object is not reactive, you may need to use `Vue.set`.

**Comment by filippolcr** [comment]
> @filippolcr It looks like you are logging the state before updating it. What makes you think that the mutation has failed? If it is that the user object is not reactive, you may need to use `Vue.set`.

Good point. Inspecting the Vue Dev Tools tipped me off. I'll try with Vue Set.

**Comment by scscgit** [comment]
I'd also like to point out that the (mutation) docs don't mention if there's any [`this.$set`](https://vuejs.org/v2/guide/reactivity.html#For-Objects) available, or if the only option is to import `Vue`'s `set`.

**Comment by danielroe** [comment]
@scscgit FYI: `vuex` doesn't support using `this` anywhere except in actions.
