### ISSUE TITLE
docs: usage with Vue.component

### ISSUE THREAD

**Issue by toomuchdesign** [danielroe/typed-vuex#215]
**📚 Is your documentation request related to a problem? Please describe.**
Docs explain how to get vuex types in class components (levaraging TS's decorators). I was wandering whether class components are mandatory or is also possible using `typed-vuex` with component instantiated via `Vue.component`.

**🔍 Where should you find it?**
https://typed-vuex.roe.dev/getting-started-vue

**ℹ️ Additional context**
Thanks for the amazing job here. I'm considering introducing store types in a legacy project and I'm trying to figure out which supporting library would better fit our codebase.

**Comment by danielroe** [comment]
@toomuchdesign It's definitely possible! Example here: https://typed-vuex.roe.dev/accessor-introduction#components-fetch-and-asyncdata - just ignore the Nuxt-specific bits if you're not using it.

**Comment by toomuchdesign** [comment]
Amazing! Looking forward to try it out. Thank you @danielroe!
