### ISSUE TITLE
Issues when accessing the state from within an action

### ISSUE THREAD

**Issue by Pitu** [danielroe/typed-vuex#233]
**🐛 The bug**
I can't access the correct state from an action.

**🌈 Expected behaviour**
When dispatching an action I should be able to read the contents of the state, yet `state.coins` is undefined here when it should be an empty array.

**ℹ️ Additional context**
```ts
import { actionTree, getAccessorType } from 'typed-vuex';

interface Coin {
	id: number;
}

interface State {
	coins: Coin[];
}

export const state = (): State => ({
	coins: []
});

export type RootState = ReturnType<typeof state>;

export const actions = actionTree({ state },
	{
		async get({ state }) {
			console.log(state) // state.coins = undefined
		}
	});

export const accessorType = getAccessorType({
	state,
	actions
});
```
This is the console.log output
![image](https://user-images.githubusercontent.com/7425261/117345888-0b475c00-aee2-11eb-8504-480e5158952e.png)

**Comment by danielroe** [comment]
@Pitu Would you provide a reproduction on CodeSandbox?

**Comment by Pitu** [comment]
Sure thing, I'll try to get a repo up and running today for you to check it out. 
Thanks a lot!
