### ISSUE TITLE
docs: use accessor outside components

### ISSUE THREAD

**Issue by Armaldio** [danielroe/typed-vuex#239]
**📚 Is your documentation request related to a problem? Please describe.**
I can't find a way to get an accessor from anywhere.
I've read the accessor part of the doc, but it's not really clear

Also, the doc say: 
![image](https://user-images.githubusercontent.com/3089715/120776936-0ac3d480-c525-11eb-8d19-a0ad34b226a5.png)

But the code also say: 
![image](https://user-images.githubusercontent.com/3089715/120776858-f2ec5080-c524-11eb-9857-760540391dff.png)

And here are my exports:
![image](https://user-images.githubusercontent.com/3089715/120777061-3050de00-c525-11eb-8902-510db152a412.png)

**🔍 Where should you find it?**
In the accessor part

**ℹ️ Additional context**

**Comment by bclermont** [comment]
Nice, an other interesting, but quickly dead project.

An other case of single-maintainer that don't want to collaborate with community contributions (ignored pull requests) and issues.

**Comment by danielroe** [comment]
You can see example code here: https://typed-vuex.roe.dev/getting-started/getting-started-vue. I hope that helps!

**Comment by nadilas** [comment]
@danielroe this is quite genius 😄 

Is there an equivalent for in nuxt2?

```
const store = new Vuex.Store(storePattern)
export const accessor = useAccessor(store, storePattern)
```

I was trying something like this, having two issues:
```
export const accessorType = getAccessorType(storePattern);

let $accessor;
const initializer = (store: Store<any>) => {
  $accessor = useAccessor(store, storePattern);
};
export const plugins = [initializer]; // makes the $accessor available out-of-component
```

Issue number 1: $access might be undefined
Issue number 2: I can't get the type right for $accessor

Any tips where to go from here?

**Comment by nadilas** [comment]
> @nadilas Could you provide a reproduction in a new issue showing how you're using it/setting up your Nuxt project?
> 
> I'm guessing for some reason https://typed-vuex.roe.dev/getting-started/getting-started-nuxt isn't working?

It is working perfectly. I am just trying to use the $accessor in a http-interceptor, which is not part of a Vue component, hence no this.$accessor

**Comment by danielroe** [comment]
I would suggest creating the interceptor in a Nuxt plugin so it's bound to the request. But it's difficult to say without more code.
