### ISSUE TITLE
Typings in monorepo

### ISSUE THREAD

**Issue by hymair** [danielroe/typed-vuex#240]
**🐛 The bug**
Our project is a monorepo of typescript nuxt apps where each app has the exact same setup as shown in the docs without any customization. The problem is that typings for `this.$accessor` are for the package that started its dev server first (I guess). Seems like all the packages share a single instance of the accessor?

**🛠️ To reproduce**
1. Create a minimal monorepo
2. Add a module in each app store
3. Check typings

**🌈 Expected behaviour**
Every package in a monorepo should have it's own context in typings.

**ℹ️ Additional context**
Editor: VSCode

**Comment by danielroe** [comment]
@hymair This sounds like an issue with VS Code; there's a known issue with TypeScript and monorepos.

Can I confirm the issue is just with the editor inference rather than the type checking run by the Nuxt dev server or build process - and that there's no issue using the accessor?

**Comment by hymair** [comment]
Yes, functionally everything works. Indeed sounds like a VSCode specific issue. Closing. Any ideas on how to deal with this?
