### ISSUE TITLE
Image link in guide not working

### ISSUE THREAD

**Issue by apgapg** [danielroe/typed-vuex#246]
Please see attached screenshot:
<img width="1552" alt="Screenshot 2021-07-26 at 5 04 12 PM" src="https://user-images.githubusercontent.com/13887407/126982426-ab561ff6-488c-4b4f-a1c6-3f658c46c77b.png">

Link: https://typed-vuex.roe.dev/

**Comment by danielroe** [comment]
Thanks - resolved in #247! ❤️
