### ISSUE TITLE
docs: Broken Link in Introduction

### ISSUE THREAD

**Issue by llMaxll** [danielroe/typed-vuex#250]
Under [https://typed-vuex.roe.dev/accessor/.accessor-introduction#typing-the-accessor](https://typed-vuex.roe.dev/accessor/.accessor-introduction#typing-the-accessor) the link of "these instructions" links to [https://typed-vuex.roe.dev/getting-started-nuxt#add-type-definitions](https://typed-vuex.roe.dev/getting-started-nuxt#add-type-definitions), which ends in a page not found.

Since I am new to this plugin and the link gets introduced with "Make sure you define types correctly" I am a bit concerned, that I am missing key informations.

Edit: I think I found the correct link: [https://typed-vuex.roe.dev/getting-started/getting-started-nuxt#add-type-definitions](https://typed-vuex.roe.dev/getting-started/getting-started-nuxt#add-type-definitions)

**Comment by danielroe** [comment]
@llMaxll Thanks for letting me know! Should be fixed in https://github.com/danielroe/typed-vuex/commit/69497fccd3b3a574ec414ec87abb34dd4d2aff72.
