### ISSUE TITLE
feat: is there a replacement for the mapState utility?

### ISSUE THREAD

**Issue by RomainBillot** [danielroe/typed-vuex#260]
First of all, awesome work, super useful.

I successfully migrated Nuxt 2 stores using your library. I'm able to use `$accessor` but I feel like using state variable in components should be simplified. (eg: $accessor.submodule.property -> property). I've done that using mapState before using typed-vuex:
```ts
export default Vue.extend({
    computed: {
        // here is the magic
        ...mapState('submodule', ['property']),
    },
})
```
But we loose the type of the freshly computed property `property`. Is there a way to keep this sugar syntaxe (not redefine every computed property, aka keep an utility for this) without loosing the types?

I think this should be documented in a new `computed properties` section?

**Comment by danielroe** [comment]
This would be quite a nice feature to add; PRs welcome!

**Comment by RomainBillot** [comment]
It you could point me to the right direction, I would make it with pleasure !
However, I'm not a Typescript Guru.

I've looked into the mapState function utility from VueX, it's quite simple : https://github.com/vuejs/vuex/blob/7651d506e473886984eab625797477d63bc69981/src/helpers.js#L9
But untyped 😭 

I'd like to have the same typed utility, like the first parameter is optional and useful for targetting a submodule, hence, the type should be keyof AccessorType? But it look like it's not working this way:
```ts
type AccessorType = typeof accessorType

// this type is = to any
type ModuleKeys = AccessorType[keyof AccessorType];

const mapAccessor = (key: ModuleKeys) => {
  // key is any here
}
```

**Comment by danielroe** [comment]
This was a great idea - thank you! Should be usable in v0.3.0...

<img width="570" alt="CleanShot 2022-02-19 at 22 59 58@2x" src="https://user-images.githubusercontent.com/28706372/154821992-67fde5b8-d350-4536-9431-18590d965049.png">
