### ISSUE TITLE
fix: namespaced property breaks code completion for modules in template in Webstorm

### ISSUE THREAD

**Issue by daniluk4000** [danielroe/typed-vuex#271]
**🐛 The bug**
When using namespaced property in modules code completion breaks for all modules in template

Possible Nuxt-only, possible Webstorm-only (works fine in `<scripts>`

**🛠️ To reproduce**
1. Open Webstorm
2. Write submodule call in template section, see TS works
3. Add namespaced: true to any other submodule
4. Code completion breaks

**🌈 Expected behaviour**
Code completion works fine

**Comment by danielroe** [comment]
Would you give an example of the kind of code that doesn't work?

**Comment by daniluk4000** [comment]
I've managed to reproduce issue in clear project.

https://github.com/daniluk4000/typed-vuex-webstorm-bug

Please try to use autocompletion in pages/index.vue for submodule and regular example property. Doesn't work for me in template, works fine in scripts section.

And then try to do the same with removing namespaced property from store/index.ts. Completion starts working for me after this. 

I've also created PR that resolves issue for me.

**Comment by daniluk4000** [comment]
I have also noticed this error with using strict property with spread operator (required in some cases for dynamic modules from #267)
